### ISSUE TITLE
Display errors in the messages?

### ISSUE THREAD

**Issue by agony09** [Yaro2709/New-Star#12]
The date and text are superimposed.
(in messages)
Is that a display bug in the script?
![New-Star_msg](https://user-images.githubusercontent.com/29257553/95679229-9f15ab80-0bd1-11eb-90cf-b6e282201163.png)

**Comment by Yaro2709** [comment]
![image](https://user-images.githubusercontent.com/51800453/95679702-464c1000-0bdd-11eb-95d7-9e1b2eb9ab7d.png)

**Comment by Yaro2709** [comment]
Какой браузер используешь? Поддержка JS есть в браузере? 
Я лично использую Google Chrome.

**Comment by agony09** [comment]
i use: Firefox 81.0 (64 bit)

**Comment by Yaro2709** [comment]
![image](https://user-images.githubusercontent.com/51800453/95680127-e60a9d80-0bdf-11eb-9c1f-b2ff1977427a.png)
у тебя не читается это. Посмотри код элемента.

**Comment by Yaro2709** [comment]
На все ошибки мне удобнее отвечать в Discorde.

**Comment by Yaro2709** [comment]
Если это так, то поставь width: 20%;
