### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xteriumboy** [Yaro2709/New-Star#27]
Message: Undefined index: details
File: /includes/GeneralFunctions.php
Line: 81
URL: http://final-space.com/game.php
PHP-Version: 7.3.27
PHP-API: litespeed
Version: 1.2.0
Debug Backtrace:
#0 /includes/GeneralFunctions.php(81): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 81, Array)
#1 /includes/common.php(194): getFactors(Array)
#2 /game.php(26): require('FILEPATH ...')
#3 {main}

**Comment by Yaro2709** [comment]
Did you install the clean version or update yourself? Try to clear your cache.

**Comment by Yaro2709** [comment]
I had no problem installing the package from the branch master. Are you sure you did everything right?

**Comment by xteriumboy** [comment]
after cache cleaned its ok now

**Comment by xteriumboy** [comment]
you can close thanks
