### ISSUE TITLE
creating modules

### ISSUE THREAD

**Issue by ragnarok22** [Yaro2709/New-Star#29]
Hi, How can I create new modules? Are any documentation about this? Thanks

**Comment by Yaro2709** [comment]
No documents. In the process.
Creating a page:
https://2moons.de/index.php?thread/602-tuto-empty-structure-of-2-files-required-for-mod-creation/

Module creation:
Go to the file includes -> constants.php
We find:
`define ('MODULE_AMOUNT', 75);`
Increase by one unit. This is the number of modifications.
We declare a new constant
`define ('MY_FIRST_MOD', 75);`
The number is assigned from the last +1.
If the last one was 74, then the next one will be 74 + 1 = 75.

After we find:
`public static $ requireModule = 0;`
And we assign the new created value:
`public static $ requireModule = MY_FIRST_MOD;`

Everything. In the admin panel, do not forget to enable and disable the new module in the modules settings, as well as in language -> EN -> ADMIN.php

**Comment by ragnarok22** [comment]
Thanks!

**Comment by Skylon2** [comment]
Thanks!
