### ISSUE TITLE
What is the DIfferent to 2moons?

### ISSUE THREAD

**Issue by wumix** [Yaro2709/New-Star#3]
Hey What is the different?
New Theme
PHP 7.3 ?

**Comment by Yaro2709** [comment]
Вы можете найти все изменения в New-Star\install\updates.txt
Поддержка php 7.3 (на 7.4 осуществляю переход).
Да, новый дизайн. 

Также, все указано [тут](https://2moons.de/index.php?thread/1050-new-star-free-download-info/&pageNo=1)
