### ISSUE TITLE
Global Message

### ISSUE THREAD

**Issue by netelite** [Yaro2709/New-Star#30]
Hello, 

Global Message doesn't work
When I try to send global message it shows:
![image](https://user-images.githubusercontent.com/61912390/115967586-c0b5ff00-a533-11eb-9be7-a8ad72f4ba3e.png)

**Comment by Yaro2709** [comment]
Version php?

**Comment by Yaro2709** [comment]
+ Show the entire error log. This is just a snippet.

**Comment by netelite** [comment]
> Version php?

PHP v7.2


> * Show the entire error log. This is just a snippet.

[24-Apr-2021 16:03:41] WARNING: "Undefined array key "act""
File: /home/soko/public_html/includes/pages/adm/ShowModulePage.class.php | Line: 35
URL: http://qspace.xyz/admin.php?page=module | Version: 1.2.0
Stack trace:
#0 /includes/pages/adm/ShowModulePage.class.php(35): errorHandler()
#1 /admin.php(73): ShowModulePage-&gt;show()
#2 {main}
[24-Apr-2021 16:05:55] WARNING: "Undefined array key "act""
File: /home/soko/public_html/includes/pages/adm/ShowModulePage.class.php | Line: 35
URL: http://qspace.xyz/admin.php?page=module | Version: 1.2.0
Stack trace:
#0 /includes/pages/adm/ShowModulePage.class.php(35): errorHandler()
#1 /admin.php(73): ShowModulePage-&gt;show()
#2 {main}
[24-Apr-2021 16:05:57] WARNING: "Undefined array key "act""
File: /home/soko/public_html/includes/pages/adm/ShowModulePage.class.php | Line: 35
URL: http://qspace.xyz/admin.php?page=module | Version: 1.2.0
Stack trace:
#0 /includes/pages/adm/ShowModulePage.class.php(35): errorHandler()
#1 /admin.php(73): ShowModulePage-&gt;show()
#2 {main}
[24-Apr-2021 16:06:01] WARNING: "Undefined array key "act""
File: /home/soko/public_html/includes/pages/adm/ShowModulePage.class.php | Line: 35
URL: http://qspace.xyz/admin.php?page=module | Version: 1.2.0
Stack trace:
#0 /includes/pages/adm/ShowModulePage.class.php(35): errorHandler()
#1 /admin.php(73): ShowModulePage-&gt;show()
#2 {main}
[24-Apr-2021 16:06:05] WARNING: "Undefined array key "action""
File: /home/soko/public_html/includes/pages/adm/ShowDumpPage.class.php | Line: 32
URL: http://qspace.xyz/admin.php?page=dump | Version: 1.2.0
Stack trace:
#0 /includes/pages/adm/ShowDumpPage.class.php(32): errorHandler()
#1 /admin.php(73): ShowDumpPage-&gt;show()
#2 {main}

**Comment by Kokito2007** [comment]
I have this error too

**Comment by Kokito2007** [comment]
SOLVED
Este error esta dado porque hay un mal redireccionamiento... buscar en ...\styles\theme\nsc\templates\adm el archivo page.sendmessages.default.tpl y modificar las lineas 10 y 23:
`'admin.php?page=sendMessages&action=send&ajax=1'`
fijarse bien que la M de Messages se escribe con mayusculas
