### ISSUE TITLE
Expedition  and Nebula Sector

### ISSUE THREAD

**Issue by Florin2090** [Yaro2709/New-Star#34]
![20210619_093757](https://user-images.githubusercontent.com/48773377/122633628-337dc980-d0e2-11eb-8da4-94f6a23cd7de.jpg)
![20210619_093625](https://user-images.githubusercontent.com/48773377/122633630-38db1400-d0e2-11eb-98dd-3c26fbce0423.jpg)
Hello, I can't send ships on an expedition, Is show the planet doesn't exist

**Comment by Yaro2709** [comment]
php version?

**Comment by Florin2090** [comment]
Solved
