### ISSUE TITLE
Buying buildings,research with dark matter

### ISSUE THREAD

**Issue by Florin2090** [Yaro2709/New-Star#35]
can't buy, error occurs
![Screenshot_20210619-101756_Chrome](https://user-images.githubusercontent.com/48773377/122634646-fa485800-d0e7-11eb-8ebe-0b2f1f41bfab.jpg)
![Screenshot_20210619-101740_Chrome](https://user-images.githubusercontent.com/48773377/122634649-fe747580-d0e7-11eb-93da-c46257c6f8b5.jpg)

**Comment by Yaro2709** [comment]
Please try these links.
/game.php?page=buyBuild
/game.php?page=buyTech

**Comment by Florin2090** [comment]
Working solved 👍
