### ISSUE TITLE
Robots and nano

### ISSUE THREAD

**Issue by leonash01** [Yaro2709/New-Star#6]
They are not working good in the way of reducing time, for nanos must be 50% and for robots must be 10% and doesn't work, and the time of nano is growing every level instead of being always the same.
Thank you,
Greetings!

**Comment by Yaro2709** [comment]
I know. But while I am writing new modifications. The balance will be posted in September.
Sincerely.
P. S. And yes, I do not make a 100% clone.

**Comment by Yaro2709** [comment]
Decision:
https://2moons.de/index.php?thread/1050-new-star-free-download-info/&postID=8666#post8666
